//GET Catalog Packing
export const GET_CONTAINERS_REQUEST = 'GET_CONTAINERS_REQUEST';
export const GET_CONTAINERS_SUCCESS = 'GET_CONTAINERS_SUCCESS';
export const GET_CONTAINERS_FAILURE = 'GET_CONTAINERS_FAILURE';
export const SCAN_BARCODE_SUCCESS = 'SCAN_BARCODE_SUCCESS';
export const SAVE_BARCODE_SUCCESS = 'SAVE_BARCODE_SUCCESS';
export const CLEAN_BARCODE_NOT_FOUND = 'CLEAN_BARCODE_NOT_FOUND';